#!/bin/bash

tmp=tmp_
cwd=`pwd`
total=0
passed=0

dir=`dirname $0`
tdir=`readlink -f $dir`
srcdir=$tdir/../src

# use ./t/pdb.directories for tests
export STAMPDIR=.
 
cd $tdir

for file in `ls *.t | sort -n`
do
    test=${file%\.t}
    source $file
    if [ $? = 0 ]
    then
	echo "test $test - ok";
	let passed++
    else
	echo "test $test - failed.";
    fi
    let total++
done

\rm stamp_rough.trans 2>/dev/null

echo "passed $passed/$total."

cd -
