#!/usr/bin/perl -w

for($i=0; $i<=$#ARGV; ++$i) {
	printf("%%Looking for string %s\n",$ARGV[$i]);
	push(@list,$ARGV[$i]);
}

$output = -1;
while(<stdin>) {
  if((!/^[%#]/) && (/\{/)) { #\}
   for($i=0; $i<=$#list; ++$i) {
     if(/$list[$i]/) { 
       print "%% FOUND ID $list[$i]\n";
       $output = 0; 
     }
   }
  }
#  print "Here output is $output\n";
  if(($output>=0) && ($output<4)) { print; } 
  #\{
  if(/\}/) { 
    $output = -1 
  }
  if($output>=0) { $output++; }
}
