#!/usr/local/bin/perl -w

for($i=0; $i<=$#ARGV; ++$i) {
	printf("%%Looking for string %s\n",$ARGV[$i]);
	push(@list,$ARGV[$i]);
}

$output = 1;
while(<stdin>) {
	if(/^[%#]/) { 
		$output = 1; 
	} elsif(/{/) {
		$output = 0;
		for($i=0; $i<=$#list; ++$i) {
			if($_ =~ /$list[$i]/) { $output = 1; }
		}
	}
	if($output ==1) { print $_; }
}
